### ISSUE TITLE
Difference to existing project?

### ISSUE THREAD

**Issue by KaySackey** [ikatyang/tslint-plugin-prettier#15]
Sorry if this is already been explained elsewhere---I could not find it.

What is the difference between this project and tslint-config-prettier[1]?

They appear to have the same goals, but a different initial setup.

[1] https://github.com/alexjoverm/tslint-config-prettier

**Comment by ikatyang** [comment]
- `tslint-config-prettier` is about disable rules that conflict with prettier's behavior, it just disabled rules.
  - I'm also having a similar project ([tslint-config-prettier-ext](https://github.com/ikatyang/tslint-config-prettier-ext)), which [will merge into that project](https://github.com/alexjoverm/tslint-config-prettier/issues/8).
- `tslint-plugin-prettier` is about running prettier as a tslint rule (plugin), so that you don't need to run prettier out of box (behave as linter rule, and also having fixer).
  - I may describe not well but their difference is similar to `eslint-config-prettier` vs `eslint-plugin-prettier`, see also [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier#readme)

**Comment by ikatyang** [comment]
I think I should update description to something like `Runs Prettier as an TSLint rule and reports differences as individual TSLint issues.`

**Comment by Falieson** [comment]
I thought with the `tslint-config-prettier` plugin, that when I run --fix it executes prettier?

**Comment by ikatyang** [comment]
Closing as people should [know what's the purpose of this project](https://github.com/ikatyang/tslint-plugin-prettier/commit/0c0562ec205b0ae049bbd5449dabf1fefb240603) now, seems no need to keep this issue opening.

**Comment by runia1** [comment]
Hi @ikatyang, great work on this project!  I was also confused at first what the difference was until finding this issue and reading your response: https://github.com/prettier/tslint-plugin-prettier/issues/15#issuecomment-322978853

Wonder if we could add a better description to the README.  Maybe include a use case for when you'd use this package and when you wouldn't. For example:

### you'd use this package when...
- you only want to run prettier as a plugin of tslint and you only want prettier to fixup `.ts` or `.tsx` files
- Ex npm script: `"lint": "tslint -p tsconfig.json"`

### you wouldn't use this package when...
- you want prettier to fixup other file types such as `.md` or `.json`.  In this case you'll need to run prettier manually as an additional step along with tslint.  For this use case it's useful to configure tslint with [tslint-config-prettier](https://github.com/prettier/tslint-config-prettier)
- Ex npm script: `"lint": "tslint -p tsconfig.json && prettier --write \"src/**/*.{ts,tsx,js,md,json}\""`

**Comment by ikatyang** [comment]
PRs welcome :)

**Comment by runia1** [comment]
Will do!
