### ISSUE TITLE
Resolve configuration using current directory

### ISSUE THREAD

**Issue by n0nick** [ikatyang/tslint-plugin-prettier#44]
In [`prettierRule.ts:38`](https://github.com/ikatyang/tslint-plugin-prettier/blob/v1.2.0/src/prettierRule.ts#L38), tslint-plugin-prettier tries to resolve a `prettier` configuration file based on the examined file's path.

Some editor integrations do fancy things such as running `tslint` on temp files (in order to catch lint errors before file save), so this breaks that. Specifically I've hit that with Vim+ALE: w0rp/ale#956.

My suggestion would be to try to fall back to the system's current directory ([`process.cwd()`](https://nodejs.org/docs/latest/api/process.html#process_process_cwd)) after trying to resolve based on file path.
This would allow the editor integration to fix this by `cd`ing into the project directory.

**Comment by ikatyang** [comment]
Thanks for the report, but I have no idea how to fix it properly since cosmiconfig (prettier use this module to find config) will lookup its file system structure to find the config file, that is, the config file can be anywhere in its parent directory, not only look at the root folder. As far as I know, caches won't remain its fs structure, they're always flattened.

In my opinion, this issue should be fixed on the editor/editor-plugin side since they touched the file path, so they should have the responsibility to correct them back, but I'm open to fix this on my side if the proposal is reasonable.

**Comment by n0nick** [comment]
Thanks for the quick response @ikatyang.

I'm not too familiar with cosmiconfig or the prettier logic, but I imagined something like the following replacing [prettierRule.ts:37-42](https://github.com/ikatyang/tslint-plugin-prettier/blob/v1.2.0/src/prettierRule.ts#L37-L42):
```
const resolved_config =
  prettier.resolveConfig.sync(source_file.fileName) ||
  prettier.resolveConfig.sync(process.cwd());
if (resolved_config !== null) {
  options = resolved_config;
}
```

If this sounds like wanted behavior for tslint-plugin-prettier, I can try and see if that would work.

**Comment by n0nick** [comment]
It even seems that cosmiconfig defaults to `process.cwd()` when no search path is specified:
https://github.com/davidtheclark/cosmiconfig#usage

**Comment by ikatyang** [comment]
Prettier CLI always find config based on its filepath:

https://github.com/prettier/prettier/blob/1.7.0/src/cli-util.js#L245
https://github.com/prettier/prettier/blob/1.7.0/src/cli-util.js#L257

I'd like to keep the same behavior with CLI so that people can move smoothly if they want to switch back to use CLI. Another solution is to specify a config file path manually, e.g.

```json
{
  "rules": {
    "prettier": [true, "path/to/config/file/based/on/cwd"]
  }
}
```

Is that looks good to you?

**Comment by n0nick** [comment]
I agree re consistency with the CLI, I see your point.

If something like what you suggest is easy to add and would work with a relative path (i.e. `"."`), that would be awesome.
Especially since I don't have a better idea for the editor plugin's side (they want to allow linting before saves, so files need to be outside of project scope).

**Comment by n0nick** [comment]
Thank you @ikatyang for the responsiveness and quick turnaround! :tada:
